version: 2.1

jobs:
  sims:
    docker:
      - image: nba_exploration
        auth:
          username: jwass2
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: Rscript tests/test_sim.R

workflows:
  test_all:
    jobs:
      - sims
